version: "3.9"
services:
  app:
    container_name: mlops_challenge
    build: .
    restart: on-failure
    environment:
      - DEPLOY_MODE=PROD
    ports:
      - 8000:8000
    volumes:
      - C:/Users/User/.cache/huggingface/hub:/root/.cache/huggingface/hub
      - C:/Users/User/projects/tst_mlops/solution/workspace:/workspace