version: "3.5"

networks:
  local:
    driver: bridge

services:

  tritonserver:
    runtime: nvidia
    build: ./triton-server
    shm_size: '16G'
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    command: git init && dvc pull
    command: tritonserver --model-repository=./models
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
    healthcheck:
        test: ["CMD", "curl", "-v", "localhost:8000/v2/health/ready"]
        interval: 30s
        timeout: 10s
        retries: 3
    networks:
      - local

  web-app:
    build: ./app
    environment:
      - TRITON_URL=tritonserver
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      tritonserver:
        condition: service_healthy
    networks:
      - local

