version: "3.9"

services:
  web:
    build: .
    image: infra_challenge
    volumes:
      - models:/models
    ports:
      - "3030:3030"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24

volumes:
  models: