version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:6.2.4-alpine
    ports:
      - '6379:6379'
